name: Compile and Publish Typst PDF

on:
  push:
    branches:
      - main

env:
  TYPST_FILE: main.typ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust and Cargo (if not already installed)
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"

      - name: Install Typst
        run: cargo install --git https://github.com/typst/typst --locked typst-cli

      - name: Compile Typst file
        run: typst compile ${{ env.TYPST_FILE }} output.pdf

      - name: Create version tag
        id: vars
        run: echo ::set-output name=version::$(date +'%Y%m%d%H%M%S')

      - name: Upload PDF to GitHub Packages
        run: |
          npm install -g @actions/artifact
          artifact upload --name compiled-typst-pdf output.pdf --path output.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
